### ISSUE TITLE
Create the query parser

### ISSUE THREAD

**Issue by gdbrown** [gdbots/query-parser-php#1]
We need the ability to generically parse a string and determine what parts of that string can be used to search on.

Review:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
http://www.searchtechnologies.com/search-query-parsing
http://elasticsearch-users.115913.n3.nabble.com/Leveraging-the-query-parser-td4023636.html
http://forum.compass-project.org/message.jspa?messageID=294616#294616

What we want to get from the query parser:
- terms (keywords to search on)
- phrases, i.e. "strings in quotes"
- hashtags
- emojis
- filters, i.e. creator:bob, plays:>500
- include/exclude (boolean operators).  e.g. cats -dogs  or +cats basketball.

The result of the query parser would be an object with the above nicely extracted out and usable to form a search operation on any platform (ES, dynamodb, map reduce, mysql, sphinx, etc.)

**Comment by gdbrown** [comment]
check out the mustache parser, or twig or the doctrine annotations lib.  all using similar char by char strategy and they have some straight forward handlings for the stuff you're running into.

btw, the boosting is at the end... e.g.  "this is boosted"^2 or, cats and dogs^2
see elastic search docs.

**Comment by bhsiao55** [comment]
Here are some bugs that I found

-The number 5000 is returned in the word bucket
-The date 2015-10-31 without a space at the end is returned in the word bucket
-1....5 causes parser to crash
-a:1....5 causes parser to crash
-1..5 is returned in the number bucket

**Comment by excelwebzone** [comment]
@bhsiao55 see latest commits for bug fix

**Comment by bhsiao55** [comment]
-1..5 is returned in numbers bucket, should be word
-a:1....5 causes parser to crash

**Comment by bhsiao55** [comment]
The below two cases should give similar results
site:       cars => returns filter with field=site, operator=:, and value=cars
site:>     cars => returns two words site:> and cars

a:>1..5 => returns field=a,operator=:>, and value = ["1","5"].  Value should not be a range cause range only makes sense with : operator
