### ISSUE TITLE
Is there a reason for the limited query length?

### ISSUE THREAD

**Issue by JC5** [gdbots/query-parser-php#19]
Took me a while to realise this little devil was breaking my queries:

https://github.com/gdbots/query-parser-php/blob/master/src/Tokenizer.php#L93

Would appreciate your input.

**Comment by gdbrown** [comment]
@JC5 i'm sure there was a reason but I can't recall exactly, I think it was a downstream schema or service was failing due to it being too long of a string.  anywho, it's removed now.. https://github.com/gdbots/query-parser-php/releases/tag/v2.0.1
