### ISSUE TITLE
ElasticaQueryBuilder to use multi-field query instead of single field for "default" field.

### ISSUE THREAD

**Issue by gdbrown** [gdbots/query-parser-php#5]
When building a query with the `ElasticaQueryBuilder` we want to be able to tell ES what fields to query on and take advantage of per field boosting and field length norms.

**Modifications needed:**
- add method to `QueryBuilder` interface "setDefaultFieldNames(array $fieldNames)" and implement in `AbstractQueryBuilder`.
- remove "final" from "setDefaultFieldName" method in `AbstractQueryBuilder`
- When setDefaultFieldName is called, add it to an array and pass to "setDefaultFieldNames".  kept for backwards compatibility.  mark `setDefaultFieldName` as deprecated in interface.
- In `ElasticaQueryBuilder` implement multi-field searching using the defaultFieldNames array instead of defaultFieldName.  https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-multi-match-query.html.  pay close attention to the different types of match queries as they will need to be tweaked.
- Add 'setMinimumNumberShouldMatch' to `ElasticaQueryBuilder`, default internal value to "2<80%".  This will be used in `getFilteredQuery`.

This will be a minor rev to 0.2.0

**Comment by gdbrown** [comment]
we may need to keep the "defaultFieldName" as some term queries use it (or modify those as well).  Let's discuss when you get to this.

**Comment by excelwebzone** [comment]
@bhsiao55 can you do some code review and some additional testing (I can provide you my test file)..

**Comment by excelwebzone** [comment]
Todo: validate that term filter (for example date) works

**Comment by excelwebzone** [comment]
@bhsiao55 please review the code and get back to me if it need any additional fixes. Thanks.

**Comment by gdbrown** [comment]
backed up locally for ref... this strategy changes as the es 2.x queries are changing.  will restart this project post 2.x updates

**Comment by gdbrown** [comment]
changed again in v5.  holding a little longer until we time to upgrade to 5.
